dashboard/urls.py
# Django
from django.urls import path

# Views
from dashboard import views

urlpatterns = [
    
    path(
        route='dashboard/',
        view=views.dashboard, 
        name='dashboard'),
    path(
        route='rfid/',
        view=views.dashboard_rfid,
        name='dashboard_rfid'),
    
]

havensecurity/urls.py
# Django

from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect
from django.views.generic import TemplateView

# Views

from dashboard import views as dashboard_views
from users import views as users_views


def index(request):
    return redirect('haven')

urlpatterns = [
    #path('admin/', admin.site.urls),
    
    path('dashboard/',include(('dashboard.urls','dashboard'), namespace='dashboard')),

    path('users/',include(('users.urls','users'), namespace='users')),
    
    path(
        route='',
        view=TemplateView.as_view(template_name = 'haven/haven.html'),
        name='haven'),
    
    path(
        route='details/',
        view=TemplateView.as_view(template_name= 'haven/details.html'),
        name='details'),
    
    path(
        route='about/',
        view=TemplateView.as_view(template_name='haven/about.html'),
        name="about"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
# Django
from django.urls import path

# Views
from users import views
urlpatterns = [

    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'),
    
    path(
        route='logout/',
        view=views.LogoutView.as_view(), 
        name='logout'),
    
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'),
]

dashboard/models.py
from django.db import models


# Create your models here.

class ID_table(models.Model):

        ids = models.IntegerField(unique=True)
        created = models.DateTimeField(auto_now_add=True)
        modified = models.DateTimeField(auto_now=True)

        def __str__(self):
                return self.user.username

users/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

users/forms.py
# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile


class SignupForm(forms.Form):

    username = forms.CharField(min_length=4, max_length=50)

    password = forms.CharField(max_length=70, widget=forms.PasswordInput)
    password_confirmation = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput
    )

    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    # Valida un solo campo

    def clean_username(self):
        """Username must be unique"""
        username = self.cleaned_data['username']
        username_query = User.objects.filter(username=username).exists()

        if username_query:
            raise forms.ValidationError('Username is already in use.')

        # Debe regresarse el campo
        return username

    def clean(self):
        """Verify password confirmation match"""
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Passwords do not match.')

    def save(self):
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)

        profile.save()

dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from dashboard.models import ID_table
# Create your views here.
import random

# Thingspeak

import urllib3
import json

#Dropbox

import dropbox
import os


dbx = dropbox.Dropbox(os.environ['DROPBOX_APIKEY'])
http = urllib3.PoolManager()

results = 10

@login_required
def dashboard(request):
    temp_values = []
    gas_values = []
    timestamp_values = []
    
    timestamp_str = http.request('GET', f'https://api.thingspeak.com/channels/1509577/fields/3.json?results={results}')
    temp_str = http.request('GET',f'https://api.thingspeak.com/channels/1509577/fields/1.json?results={results}')
    gas_str = http.request('GET',f'https://api.thingspeak.com/channels/1509577/fields/2.json?results={results}')
    timestamp = json.loads(timestamp_str.data)
    temp = json.loads(temp_str.data)
    gas = json.loads(gas_str.data)
    
    for i in range(results):
        
        temp_values.append(temp['feeds'][i]['field1'])
        gas_values.append(gas['feeds'][i]['field2'])
        
        aux = timestamp['feeds'][i]['field3']
        if(aux == None):
            timestamp_values.append('0')
        else:
            timestamp_values.append(aux[:4]+'-'+aux[4:6]+'-'+aux[6:8]+' | '+aux[9:11]+':'+aux[11:13]+':'+aux[13:15])
        
    return render(request, 'dashboard/dashboard.html', {
        'results': results,
        'time': timestamp_values,
        'gas': gas_values,
        'temp': temp_values,
    })


@login_required
def dashboard_rfid(request):
    path_dbx = '/home/pi/HavenSecurity_IoT/codes'
    photo_id = 'https://www.dropbox.com/s/xmn3neyx9xkqit7/imagen_151_1.jpg?dl=0'
    ids = {}

    list_folder = dbx.files_list_folder(path_dbx)
    files = [list_folder.entries[idx].name for idx, value in enumerate(list_folder.entries)]
    for f in files:
        ids[f.split('_')[1]] = (dbx.files_get_temporary_link(path_dbx+'/'+f)).link
    
    if request.method == 'POST':
        new_ids = request.POST['photo_id_change']
        
    return render(request, 'dashboard/dashboard_rfid.html', {
        'photo_id': photo_id,
        'ids': ids,
    })

users/views.py
"""User views"""
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from django.urls import reverse_lazy

# Forms

from users.forms import SignupForm

# Create your views here.

class LoginView(auth_views.LoginView):
    """Login View

    Args:
        auth_views ([type]): [description]
    """
    
    template_name = 'users/login.html'
    

class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    
    template_name = 'users/logout.html'
    
    next_page = 'haven'



class SignupView(FormView):
    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

templates/base.html
<!DOCTYPE html>
<html>
{% load static %}
    {% block head_content %}

        <title>  Haven Security</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    {% endblock %}


    {% load static %}
    <link rel='stylesheet' href="{% static '/css/main.css' %}">
    <link rel='stylesheet' href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% block navbar %}
        {% include 'navbar.html' %}
    {% endblock %}

    {% block content %}{% endblock %}

</html>

templates/dashboard/base.html
<!DOCTYPE html>
<html>
{% load static %}
    {% block head_content %}

        <title>  Haven Security</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    {% endblock %}


    {% load static %}
    <link rel='stylesheet' href="{% static '/css/main.css' %}">
    <link rel='stylesheet' href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% block navbar %}
        {% include 'dashboard/navbar.html' %}
    {% endblock %}

    {% block content %}{% endblock %}

</html>

templates/dashboard/dashboard.html
{% extends 'dashboard/base.html' %}

{% block head_content %}
    <title>Dashboard</title>
{% endblock %}

{% block content %}

{% load static %}
<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Sensores</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'dashboard:dashboard' %}">
              <span data-feather="home"></span>
              Temperatura y Gas
            </a>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dashboard:dashboard_rfid' %}">
              <span data-feather="users"></span>
              RFID y Camara
            </a>
          </li>
          
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Cuenta</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">
              <span data-feather="file-text"></span>
              Logout
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
      </div>

<!------------THINGSPEAK----------->
    <div class="row">
        <div class="col-lg-8">
            <iframe width="450" height="260" style="border: 1px solid #cccccc;" src="https://thingspeak.com/channels/1509577/charts/1?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&type=line&update=15"></iframe>
          </div>
        <div class="col-lg-8">
            <iframe width="450" height="260" style="border: 1px solid #cccccc;" src="https://thingspeak.com/channels/1509577/charts/2?bgcolor=%23ffffff&color=%23d62020&dynamic=true&results=60&type=line&update=15"></iframe>
        </div>
    </div>
    <h2 class="w3-wide w3-serif">Enciende y apaga el ventilador</h2>
    <button id="b_on" onclick="ventilador_on()" class="btn btn-dark">ON</button>
    <button id="b_off" onclick="ventilador_off()" class="btn btn-dark">OFF</button>

    <!--------TABLE--------->

        <h2>Section title</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Fecha</th>
              <th scope="col">Temp</th>
              <th scope="col">Gas</th>
            </tr>
          </thead>
          <tbody>
          {{ context }}
          {% for t in time %}
          {% for g_value in gas %}
              {% for t_value in temp %}
              
            <tr>
                <td>#</td>
              <td>{{ t }} </td>
              <td>{{ t_value }}°C</td>
              <td>{{ g_value }} ppm</td>
            {% endfor %}

            </tr>
          {% endfor %}
          {% endfor %}
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>
<script>
  function ventilador_on() {
    var xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function() {
      if (this.readyState == 4 && this.status == 200) {
        Exito_on = this.responseText;
      }
    };
    xhttp.open("POST", "https://api.thingspeak.com/update?api_key=MT0JJEJYRP9MXT7X&field4=1", true);
    xhttp.send();
    
  }
  function ventilador_off() {
    var xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function() {
      if (this.readyState == 4 && this.status == 200) {
        Exito_off = this.responseText;
      }
    };
    xhttp.open("POST", "https://api.thingspeak.com/update?api_key=MT0JJEJYRP9MXT7X&field4=0", true);
    xhttp.send();
    
  }
</script>


{% endblock %}

templates/dashboard/dashboard_rfid.html
{% extends 'dashboard/base.html' %}

{% block head_content %}
    <title>Dashboard</title>
{% endblock %}

{% block content %}

{% load static %}
<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Sensores</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'dashboard:dashboard' %}">
              <span data-feather="home"></span>
              Temperatura y Gas
            </a>
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'dashboard:dashboard_rfid' %}">
              <span data-feather="users"></span>
              RFID y Camara
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Cuenta</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">
              <span data-feather="file-text"></span>
              Logout
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
      </div>


      <img src="{{ photo_id }}" alt='' style='width: 100px'>

        <h2>RFID y Fotos</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">ID</th>
              <th scope="col">Foto</th>
            </tr>
          </thead>
          <tbody>
          {{ context }}
          {% for key, value in ids.items %}
            <tr>
                <td>#</td>
                <td>{{ key }}</td>
              <td>
                <a href="{{ value }}">Img</a>
              </td>


            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </main>
  </div>
</div>



{% endblock %}

templates/dashboard/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Fifth navbar example">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'haven' %}">HavenSecurity</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample05">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'dashboard:dashboard' %}">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>

templates/haven/about.html
{% extends 'base.html' %}


{% block head_content %}
    <title>Detalles</title>
{% endblock %}

{% block content %}

{% load static %}


 <div class="container" id="descriptions_about">
    <p></p>
      <div class="row">
        <div class="col-lg-4">
          <img class="img-fluid" src="{% static 'img/Joan.jpeg' %}" alt="Generic placeholder image" width="300" height="300">
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-8">
            <h2>Joan Ferney Muñoz</h2>

          <p>Estudiante de noveno semestre de ingeniería electrónica, con énfasis en telecomunicaciones
              ,con habilidades en el manejo de programas como Altium Designer y orCAD;
              análisis, diseño de redes de telecomunicaciones básicas y seguridad en redes.</p>
          <p><a class="btn btn-dark" href="https://www.linkedin.com/in/joan-ferney-mu%C3%B1oz-tarazona-04a88620a/" role="button">Detalles &raquo;</a></p>
        </div>
      </div>
    <p></p>
        <div class="row">
            <div class="col-lg-4">
              <img class="img-fluid" src="{% static 'img/Carlos.jpeg' %}" alt="Generic placeholder image" width="300" height="300">
              </div>
                <div class="col-lg-8">
                <h2>Carlos Andres Tuiran</h2>
              <p> Estudiante orientado a la planeación y acción con pasión por la programación y
                  automatización. Tengo conocimientos en las áreas de telecomunicaciones con la
                  capacidad de manejar el programa de simulación Packet Tracer.</p>
              <p><a class="btn btn-dark" href="https://docs.google.com/document/d/1OulnlW_zVC40auX5bitepOwdrdvJ5ZW5/edit?usp=sharing&ouid=113435703447605517676&rtpof=true&sd=true" role="button">Detalles &raquo;</a></p>
            </div><!-- /.col-lg-4 -->
        </div>
    <p></p>
        <div class="row">
            <div class="col-lg-4">
              <img class="img-fluid" src="{%  static 'img/Mauricio.jpg' %}" alt="Generic placeholder image" width="300" height="300">
            </div>
            <div class="col-lg-8">
                <h2>Mauricio David Cuello</h2>
              <p>Estudiante de ingeniería con gran interés en temas como la ciencia de datos y la ciberseguridad.
                  Tengo experiencia en programacion con los lenguajes Python y C, así como conocimiento en bases de
                  datos relacionales con SQL y nivel intermedio en el uso de Linux</p>
              <p><a class="btn btn-dark" href="https://www.linkedin.com/in/mauricio-cuello-a1369b1b5/" role="button">Detalles &raquo;</a></p>
            </div><!-- /.col-lg-4 -->
        </div>



    </div><!-- /.container -->


{% endblock %}

templates/haven/details.html
{% extends 'base.html' %}


{% block head_content %}
    <title>Detalles</title>
{% endblock %}

{% block content %}

{% load static %}


    <p>Funciona</p>



{% endblock %}

templates/navbar.html
{% url 'about' as about %}
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav" >
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'haven' %}">HavenSecurity</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'dashboard:dashboard' %}">Dashboard</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}">Iniciar Sesion</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'users:signup' %}">Registrarse</a></li>
                        {% endif %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">Creadores</a></li>
                        <li class="nav-item"><a class="nav-link" href="#about">Sobre</a></li>
                        <li class="nav-item"><a class="nav-link" href="#projects">Componentes</a></li>
                        <li class="nav-item"><a class="nav-link" href="#contact">Contacto</a></li>
                    </ul>
                </div>
            </div>
</nav>

templates/users/login.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Login</title>
{% endblock %}

{% block content %}

    {% load static %}
    <div class="container" id="auth-container">
        <div class="row" id="auth-row">
            <form method="POST" action="{% url 'users:login'%}" id="form-login">
                {% csrf_token %}
                <!--img class="mb-6" src="{% static 'img/Logo.png' %}" alt='' id="login-logo" width="400" height="150" style="position: center;"-->
                <h1 class="h3 mb-3 fw-normal">Sign in</h1>
                {% if form.errors %}
                    <p class="alert alert-danger"> Usuario o contraseña no es correcto</p>
                {% endif %}
                <div class="form-floating">
                  <input type="text" class="form-control" id="username" name='username' placeholder="name@example.com">
                  <label for="floatingInput">Nombre de usuario</label>
                </div>
                <div class="form-floating">
                  <input type="password" class="form-control" id="password" name="password" placeholder="Password">
                  <label for="floatingPassword">Contraseña</label>
                </div>
                <p></p>
                    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
                <p class="mt-5 mb-3 text-muted">&copy; 2021 Havensecurity</p>
            </form>
        </div>
    </div>
{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}

{% block head_content %}
    <title>Sign up</title>
{% endblock %}

{% block content %}

    {% load static %}
    <div class="container" id="auth-container">
    <div class="row" id="auth-row">
        <form method="POST" action="{% url 'users:signup'%}">
            {% csrf_token %}
            <!--img class="mb-6" src="{% static 'img/Logo.png' %}" alt='' id="login-logo" width="400" height="150"-->
            <h1 class="h3 mb-3 fw-normal">Registro</h1>
            {% if form.errors %}
                <p> {{ form.errors }}</p>
            {% endif %}
            <div class="form-floating">
              <input type="text" class="form-control" id="first_name" name='first_name' placeholder="name@example.com" required="true">
              <label for="floatingInput">Nombres</label>
            </div>
            <div class="form-floating">
              <input type="text" class="form-control" id="last_name" name='last_name' placeholder="name@example.com" required="true">
              <label for="floatingInput">Apellidos</label>
            </div>
            <div class="form-floating">
              <input type="text" class="form-control" id="username" name='username' placeholder="name@example.com" required="true">
              <label for="floatingInput">Nombre de usuario</label>
            </div>
            <div class="form-floating">
              <input type="email" class="form-control" id="email" name='email' placeholder="name@example.com" required="true">
              <label for="floatingInput">Correo</label>
            </div>
            <div class="form-floating">
              <input type="password" class="form-control" id="password" name="password" placeholder="Password" required="true">
              <label for="floatingPassword">Contraseña</label>
            </div>
            <div class="form-floating">
              <input type="password" class="form-control" id="Password_confirmation" name="password_confirmation" placeholder="Password" required="true">
              <label for="floatingPassword">Confirmacion contraseña</label>
            </div>

            <p></p>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Registrarse</button>
            <p class="mt-5 mb-3 text-muted">&copy; 2021 Havensecurity</p>
        </form>
    </div>
</div>
{% endblock %}